### ISSUE TITLE
`pod try DTCollectionViewManager` is broken

### ISSUE THREAD

**Issue by fatuhoku** [DenHeadless/DTCollectionViewManager#13]
When I press 'run' this is what happens:

![screen shot 2015-10-03 at 15 36 41](https://cloud.githubusercontent.com/assets/430233/10263375/98e4a2f0-69e4-11e5-90b2-2ea142ff38f1.png)

**Comment by DenHeadless** [comment]
Hi.

This is because currently i use Carthage and git submodules to resolve dependency graph. I was hoping to fix pod try by using cocoapods-try customization file, but it does not seem to work right now:

https://github.com/CocoaPods/cocoapods-try/issues/40

Until this issue is resolved, you can run example project by cloning and running carthage update( or simply by pulling all git submodules)

https://github.com/DenHeadless/DTCollectionViewManager#running-example-project

**Comment by fatuhoku** [comment]
@DenHeadless Cool thanks for the note!

**Comment by DenHeadless** [comment]
I'm reopening this until pod try is available for a framework.

**Comment by DenHeadless** [comment]
Starting with 4.5.2 release, pod try is now supported.

Note - you need cocoapods at least of 1.0.0-beta2 version.
